Modify deploy.yml file

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -13,27 +13,18 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v2
 
-      - name: Build React app
-        run: npm ci && npm run build
-
       - name: Configure known hosts
         run: |
           mkdir -p ~/.ssh
           touch ~/.ssh/known_hosts
           ssh-keyscan -t rsa 54.37.204.231 >> ~/.ssh/known_hosts
-
-      - name: Update server code
+      - name: Update server code and build the React app
         run: |
-          if sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no ubuntu@54.37.204.231 "cd /var/www/html/academix-learning-system-backend/ && sudo git pull --rebase origin main"; then
-            echo "Server code update successful."
+          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no ubuntu@54.37.204.231 "cd /var/www/html/academix-learning-system-frontend/ && sudo git pull --rebase origin main && npm ci && npm run build"
+          # Check the exit code of the SSH command
+          if [ $? -eq 0 ]; then
+            echo "SSH connection, code update, and build successful."
           else
-            echo "Failed to update server code."
-          fi
-
-      - name: Deploy to Apache server
-        run: |
-          if sshpass -p ${{ secrets.SSH_PASSWORD }} scp -o StrictHostKeyChecking=no -r ./dist/* ubuntu@54.37.204.231:/var/www/html/academix-learning-system-frontend; then
-            echo "Deployment to Apache server successful."
-          else
-            echo "Failed to deploy to Apache server."
+            echo "Failed to establish SSH connection, update the code, or build the app."
+            exit 1
           fi
